# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ruta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodigoRuta', models.IntegerField(null=True)),
                ('IdConductor', models.IntegerField(null=True)),
                ('Codigo_Vehiculo', models.IntegerField(null=True)),
                ('Lugares', models.IntegerField(null=True)),
            ],
        ),
    ]
