# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ruta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='CodigoRuta',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
